### ISSUE TITLE
Good project, very nice

### ISSUE THREAD

**Issue by BenStigsen** [MadsLudvig/BigAss3DPronter#1]
Hey in line 30 of <nofile> (lol no code embarrasing) there's an error :D 

UwU

**Comment by MadsLudvig** [comment]
You makin me feel all crazy.. Hypothetically, can you walk near the bush aha hnnnn..

**Comment by BenStigsen** [comment]
Man y u closing the issue!?!? dont act like there ain't no issue fooL!

**Comment by MadsLudvig** [comment]
Benjamin Stigsen skrev den 2021-03-08 10:21:

> Man y u closing the issue!?!? dont act like there ain't no issue fooL!
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

Man imma wack u ass. You picked the wrong fool, fool!

Links:
------
[1] 
https://github.com/MadsLudvig/BigAss3DPronter/issues/1#issuecomment-792610964
[2]

**Comment by BenStigsen** [comment]
🍆
